eureka:
  instance:
    home-page-url: http://${APOLLO_HOMEPAGE:localhost:8070}
spring:
  security:
    cas:
      client:
        host: ${eureka.instance.home-page-url}
        login-url: /login/cas
        logout-url: /user/logout
      server:
        host: https://login.genomics.cn
        login-url: /cas
        logout-url: /cas/logout